dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - name="fail2web"
  - image="monogramm/docker-fail2web:travis"
  - dir="."

script:
  - travis_retry docker build -t "$image" "$dir"

after_script:
  - docker images
  - docker run --name "$name" -e FAIL2REST_PASSWD_COST=4 -d "$image" "$dir"
  - docker ps
  - docker logs "$name"

notifications:
  email: false

env: # Environments
